# Generated by Django 2.2.2 on 2019-06-24 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190624_1325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
