# Generated by Django 2.2.2 on 2019-06-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='view_time',
            field=models.IntegerField(default=0),
        ),
    ]
